language: node_js
node_js:
- 10
deploy:
  provider: npm
  email: j@jeromefitzgerald.com
  api_key:
    secure: kXGIbXJyZz9jpr1EGOuFqX7gvAusyCfeAFU0QchoXdTV5geHnNIsuBXdWH3nRfbBiLixdbOd+TgSfQ6UCsZh2DU0TxFK9Vh4fJNltt213D3B9YXmfpsGYFV6rsAR4MiVtgpOovOs24pO+FeMXFjdddNS5EgnL8d2ygMUyejxd0Sm3hZS3AqcsZgSlECmsiyw8L83KU/XwGIAPdk6nVhH3JM0wuCVOAubGusNbEILzeIA0ZC/pQfcA/07Lpm1CzbX1oaH3NcgzoIcZ9XXm+R6RxI2fMOAuSAp1guvbj5H9e0rWD3+xqUeoaPDrJVAabHfX9coyr8VVpO9ExcekektKu9VIH8r5WfT+ZUtpYZNkuvjUuS1Glz04lP2q5ZKjqABODSMkRQskKTStX93qRL8StHdYbBozgqIFFrCIpWqtFCY3QeLCYBeBpdvB8E0LdCxfjNkfnNsIff2Symq8jBVM9WQL/DxXpAKOeDKyaDKC7NWp7INQFX8/NgIfCRVQiUGesUPNvWcNVkL0RJyedEg60oyUf3zTwbYmUmQGRtmXfpx5dwjanK1ACUJyX1fsGqHC4M1kc0Fg1gQBi868CnWfomDgxbRloIy4DsTPuBUf8KVmykZRzNMmTSz9SzwRJre1LklYExXXuIjk41tnoyBOMpvzUtzereZcsD6pgseQF0=
  on:
    tags: true
  skip_cleanup: true
tag: next
before_deploy:
- npm run build
- rm .gitignore
